# Reference for yaml configuration is taken from https://github.com/LibreTranslate/LibreTranslate/blob/main/k8s.yaml
#--------------------------------
# LibreTranslator 
#---------------------------------
# ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: libretranslate-config
  labels:
    data: config  
data:
  languages: "en,es,fr"
  redis_host: "NOTSET"
  redis_port: "6379"
---
# Deployment for LibreTranslate
apiVersion: apps/v1
kind: Deployment
metadata:
  name: libretranslate-deployment
  labels:
    app: libretranslate  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: libretranslate
  template:
    metadata:
      labels:
        app: libretranslate
    spec:
      containers:
      - name: libretranslate
        image: libretranslate/libretranslate:latest
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
        env:
        - name: "LT_LOAD_ONLY"
          valueFrom:
            configMapKeyRef:
              name: libretranslate-config
              key: languages
        - name: "REDIS_HOST"
          valueFrom:
            configMapKeyRef:
              name: libretranslate-config
              key: redis_host
        - name: "REDIS_PORT"
          valueFrom:
            configMapKeyRef:
              name: libretranslate-config
              key: redis_port
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: libretranslate-svc
  labels:
    app: libretranslate    
spec:
  type: NodePort  # Changed the service type to NodePort because LoadBalancer throws localhost refused to connect
  selector:
    app: libretranslate
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    nodePort: 30001
    protocol: TCP
---
#--------------------------------
# Redis for Caching
#---------------------------------
# Redis Service
apiVersion: v1
kind: Service
metadata:
  name: libretranslate-redis-svc
  labels:
    app: libretranslate-redis
spec:
  ports:
  - port: 6379  # Redis default port
    targetPort: 6379
  selector:
    app: libretranslate-redis
---

# Redis StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: libretranslate-redis
  labels:
    app: libretranslate-redis
spec:
  serviceName: libretranslate-redis-svc
  replicas: 1
  selector:
    matchLabels:
      app: libretranslate-redis
  template:
    metadata:
      labels:
        app: libretranslate-redis
    spec:
      containers:
      - name: libretranslate-redis
        image: redis:latest
        ports:
        - containerPort: 6379  # Corrected port to match Redis default port
          name: redis-port
        volumeMounts:
        - name: redis-data
          mountPath: /data/db
        - name: redis-config
          mountPath: /data/configdb
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests: 
            storage: 10Mi
    - metadata:
        name: redis-config
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests: 
            storage: 5Mi